# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160718_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='Classification',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='classification',
            new_name='cate',
        ),
    ]
