# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160721_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cate',
            new_name='category',
        ),
    ]
